### ISSUE TITLE
Problems with the spaces option

### ISSUE THREAD

**Issue by Dantemss** [dollarshaveclub/shave#102]
Hello, I have encountered the following strange behavior when trying to shave an english text while preserving whole words (instead of splitting on any letter) in the following releases:

2.0.4: Defaults to splitting on any letter. Passing `{spaces: true}` makes it split on spaces. Probably the closest to what I would expect to happen.
2.1.2: spaces option has no effect at all(likely because of https://github.com/dollarshaveclub/shave/pull/98). Changing the source to `spaces = false` makes it split on spaces (the opposite of 2.0.4? seems odd considering the default was changed in this version and at odds with the use for non-spaced languages)
2.2.0 and 2.2.1: spaces option has no effect at all
The version that is in the codepen demos (says 2.2.0 but I'm not so sure it actually matches that release): Works like 2.1.2, but you can actually pass in `{spaces: false}` without editing the source.

Additionally, when splitting on spaces the space itself is removed (this differs from the behavior when splitting on any character, where spaces are always preserved). It would be nice if the space that was split on could be kept in the hidden span to make it easier to implement a button to show/hide the rest of the text.

**Comment by yowainwright** [comment]
Hello @Dantemss, I'm not clear on this issue as described above. 😁
- What's wrong? 
- What's desired?

Could you provide a CodePen which illustrates the issue that you're seeing? It would be easiest for me if you referenced the code that is in master vs multiple versions.

~Thanks

**Comment by Dantemss** [comment]
Hello and thanks for looking into this.

You can see on the codepen example posted in the readme (https://codepen.io/yowainwright/pen/VKVXRa), now that it has been updated, that the newest version of shave seems to always split the sentences on arbitrary letters now. For example, the word `hendrerit` becomes `he…`, no matter if you pass in `{spaces: true}` or `{spaces: false}`. Shave used to split sentences on whole words if you passed in `{spaces: true}` in 2.0.4, meaning it would abbreviate the lorem ipsum as something like `(…) non posuere justo…`.

However, it seems that splitting on whole words was not necessary in my project at the moment, so I'm not actually using this option right now.

**Comment by yowainwright** [comment]
@Dantemss yes, that's a bug. Thanks for letting me know!
