### ISSUE TITLE
Support for ex and other units

### ISSUE THREAD

**Issue by DanielRuf** [dollarshaveclub/shave#116]
## What Is the issue?
It seems currently we can not use `ex` and other units to set the desired height.

## Provide issue context below using code examples, images, or links

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
@DanielRuf to keep the shave utility minimal, using the default javascript unit measure (pixels) is used.

**Comment by DanielRuf** [comment]
Sure, I'm totally aware of the fact that we want to keep it as minimal as possible. But why not provide a description or option to support `ex` (`calc()` and others support it)?

Also see https://2012.heygrady.com/blog/2011/12/21/length-and-angle-unit-conversion-in-javascript/

https://stackoverflow.com/questions/20462388/measure-ex-in-px-in-javascript

**Comment by yowainwright** [comment]
The sentence referenced below (which is located at the top of the [README](https://github.com/dollarshaveclub/shave/blob/master/README.md)) could be more clear _max-height in pixels_. 

> Shave is a zero dependency javascript plugin that truncates multi-line text to fit within an html element based on a set max-height.

**Comment by DanielRuf** [comment]
Thanks for the update.

> This utility 

Do you mean shave?

**Comment by yowainwright** [comment]
@DanielRuf yup! 😀
