### ISSUE TITLE
types missing when installing from npm

### ISSUE THREAD

**Issue by snaptopixel** [dollarshaveclub/shave#127]
## What Is the issue?

I see types in the repo but they don't end up in the node_modules folder when installing via yarn

## Provide issue context below using code examples, images, or links

If I `yarn install dollarshaveclub/shave` I get all the files

**Comment by yowainwright** [comment]
Oooops. I'm sorry about [this (issue in "this" link)](https://github.com/dollarshaveclub/shave/blob/master/package.json#L8-L11). 

In the `package.json`, this is needed (from the [npm docs](https://docs.npmjs.com/files/package.json#files)) .
```json

"files": [
    "dist",
    "src",
    "types"
  ],

```
Do you want to submit a PR or shall I?

**Comment by snaptopixel** [comment]
I gotchu @yowainwright 😉

**Comment by yowainwright** [comment]
Thanks @snaptopixel!!! 🙏
