### ISSUE TITLE
SVG foreignObject support ?

### ISSUE THREAD

**Issue by cloud-tribal** [dollarshaveclub/shave#139]
## What Is the issue?
Text does not truncate properly in a foreignObject in SVG.
1- Codepen below truncates whole text
2- When integrating into Vue app with SVG, text renders as **â€¦**

## Provide issue context below using code examples, images, or links
https://codepen.io/anon/pen/eQwNEY
----

**Comment by yowainwright** [comment]
Dig into the [css used](https://codepen.io/yowainwright/pen/WYqpdZ). 

Here's an example with 1 css rule [change](https://codepen.io/yowainwright/pen/WYqpdZ).
