### ISSUE TITLE
Shave strips inner HTML

### ISSUE THREAD

**Issue by stephwestgarth** [dollarshaveclub/shave#143]
As the title says, shave strips any inner HTML from the text block as it's using textContent or innerText. 

The most basic of examples, I've just replaced the first paragraph in the example codepen with the following:

`Here is some example text with an <em>italicised</em> piece of text. It also may have some text with a <span class="bold">span containing a bold class</span> on it. I'm just writing something to make this text longer so you can plug it into any of your examples and see it (not) work. `

Codepen with the text above in it: https://codepen.io/anon/pen/PVeXMW

This obviously causes problems if you have any formatting in your element you're trying to shave.

**Comment by yowainwright** [comment]
Hello @stephwestgarth. thanks for your feedback. 

What you're describing is expected. 

The reason "shave" was written to be scoped to a single element was to avoid miscalculation and provide the smallest most precise api possible to shave text from a single element. If there is a feeling of miscommunication in this goal, pull requests for README updates will be reviewed.

**Comment by stephwestgarth** [comment]
Hi Jeff,

I think this isn't necessarily made clear as it's just a footnote down at the very bottom of the page only within the readme file. It isn't at all mentioned on the page on GitHub pages url which is what you're sent to first from the description, which has almost identical content to the readme file. I'll admit I didn't check the readme file carefully for this fact until you mentioned it here because the pages are so similar and the note is missing from that page.

Furthermore to this, the notes section is replaced on this page with comparisons to other libraries that all have this feature, therefore making the comparisons somewhat misleading. The removal of these features is almost certainly one of the main reasons why it's faster. It'd be clearer to me if the statement was something more like "Shave is faster in comparison to similar libraries like (library list) because of it's clean and simple single-element only approach." Still positive and would fit a lot of use cases for most (I would think), but it also gives the reader a better idea of why there is such a big time improvement.

Removing any formatting tags on text is a big drawback on the library for the use cases we are working with. Even the most simple of formatting tags don't make it through. It's fine if you don't want to include the feature (there are other options available) but make it clear in all locations, particularly the landing page where people will look to find out more information about the library and not just at the very bottom of the readme file.

The library is great and you've done a fantastic job; it was just disappointing to find out it was missing something that seemed obvious to preserve from our point of view and therefore we won't be able to use it for our projects.

**Comment by eballeste** [comment]
the very thing i was trying to figure out...

**Comment by digitalcraft** [comment]
Any chance you can open this up again?
This is an obvious cause of an XSS attack vector.
If an application has escaped HTML entities, and you fetch innerTEXT of this and then insert it with innerHTML into another entity, you are bypassing the XSS protection.

**Comment by jakiestfu** [comment]
@digitalcraft Does shave actually do that though? I don't think so... At most, I'm seeing it use `insertAdjacentHTML`. Where is the XSS issue?

**Comment by digitalcraft** [comment]
https://jsfiddle.net/32795mpy/
