### ISSUE TITLE
Give minified version and also include the current version in shave.js

### ISSUE THREAD

**Issue by kwoxer** [dollarshaveclub/shave#16]
First of all awesome tool! I compared the execution time of a big page on an actual project.

With trunk8 it was ~550ms and with shave it ist ~6ms. Really awesome!

But as the title says. It would be awesome if you could add the version number to the js file and also add add a minified version. Also if it's not really needed. But saving additional space it not bad ;)

**Comment by yowainwright** [comment]
Hey @kwoxer , 

That's a great thought as far as the version number - I'll talk that over with the rest of the team today. 

As far as minified a version, I'm interested in hearing your opinion there (?). 🤔

~THANKS 🍻

**Comment by yowainwright** [comment]
@kwoxer Thanks for your notes. UPDATED

**Comment by kwoxer** [comment]
Ohh sorry, didn't see this one. Thank you very much again for the fast adding of the minified version.

**Comment by yowainwright** [comment]
@kwoxer Thanks for pointing out & detailing the issue. 🙌
