### ISSUE TITLE
Usage of insertAdjacentElement broke shave.js for Firefox < 48

### ISSUE THREAD

**Issue by amoshydra** [dollarshaveclub/shave#169]
## What Is the issue?
PR #145 (https://github.com/dollarshaveclub/shave/pull/145/commits/fb9feb8d44419abcdde419f44a16a1150ad59932) introduced usage of `insertAdjacentElement` into shave.js. However `insertAdjacentElement` is not supported by Firefox < v48

This issue affect shave [v2.5.3](https://github.com/dollarshaveclub/shave/releases/tag/2.5.3) and above

## Provide issue context below using code examples, images, or links
![image](https://user-images.githubusercontent.com/8733840/63160375-2f00a980-c050-11e9-9585-8a83c9a13a4a.png)
https://caniuse.com/#feat=insert-adjacent

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
This issue will not be fixed because of Firefox auto-updates while `insertAdjacentElement` supports older versions of Internet Explorer. 

Thank you for this thoughtful issue and PR. :pray:
