### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by jrean** [dollarshaveclub/shave#17]
Hi,

Awesome package!
Can you please think to add (or to provide guidance) about what `dotdotdot` is providing (super useful):

```
dot-resize-update - automatically update if window resize event occurs. It's equivalent to option watch:'window'.

dot-timer-update - automatically update if window resize event occurs. It's equivalent to option watch:true.

dot-load-update - automatically update after the window has beem completely rendered. Can be useful if your content is generated dynamically using JS and, hence, jQuery.dotdotdot can't correctly detect the height of the element before it's rendered completely.
```

Cheers

**Comment by yowainwright** [comment]
Hey @jrean ! 

As I'm sure you know, events - like window resize, are very [expensive](https://www.paulirish.com/2009/throttled-smartresize-jquery-event-handler/).

Shave will not be adding events. This allows the user of the plugin to ensure that they control events & don't get unexpected performance costs as a result of using the plugin.

Maybe we could add a few lines in the readme with some notes on how a user of the plugin might want to use shave within an event ... ?

**Comment by jrean** [comment]
> Maybe we could add a few lines in the readme with some notes on how a user of the plugin might want to use shave within an event ... ?

It would be awesome.

Thank you again for your fantastic work!

**Comment by yowainwright** [comment]
@jrean very basic examples are added to the README. Thanks for the note. 🙌
