### ISSUE TITLE
need support for East-Asian languages

### ISSUE THREAD

**Issue by Diablohu** [dollarshaveclub/shave#18]
Here's an example: http://codepen.io/Diablohu/pen/ORKejx

**Comment by yowainwright** [comment]
http://codepen.io/yowainwright/pen/wzVgMp 🤓 🙌  

Worked on that yesterday - It was updated 2 versions ago. 

Please let me know if it could be improved. ~Thanks

**Comment by Diablohu** [comment]
Haven't noticed that update. I just forked and tested the Pen listed on the project home page. Thanks anyway and keep the great work on!
