### ISSUE TITLE
Trim hidden elements with display:none style

### ISSUE THREAD

**Issue by kirylpl** [dollarshaveclub/shave#183]
## What Is the issue?

It's impossible to Trim hidden elements with `display:none` style now.
Could we have this as an option?

## Provide issue context below using code examples, images, or links

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
Hey, @kirylpl!

This is an issue that can be fixed outside of the Shave utility...

The **"shaved"** element could be selected and a `display: default` or similar style could be set to child elements right before **"shaving"** to achieve the result requested in this issue.  

Shave is a utility for simplicity and speed so features (like this) will not be added.

Thanks for the thoughtful request! :pray:
