### ISSUE TITLE
Why use max-height in parameters and not from css ?

### ISSUE THREAD

**Issue by ryuran** [dollarshaveclub/shave#19]
Hello

Usually with dotdotdot.js we do not give max-height as parameter.
Dotdotdot use css max-height property.
Why shave.js do not ?

**Comment by yowainwright** [comment]
Shave uses a max height to truncate text. I apologize but I'm unclear to your request ... ?

**Comment by ryuran** [comment]
Why use a declarative maxHeight by parameters in javascript and not `getComputedStyle(el)['max-height']`? @yowainwright

**Comment by borisschapira** [comment]
@ryuran you can still use a ruse, calling shave in a function that gets the current css max-height property and pass it to shave.

**Comment by ryuran** [comment]
@borisschapira yes I know.
The question was "why this choice?"

**Comment by yowainwright** [comment]
@borisschapira thanks for your response. As stated - we know what @borisschapira wrote is correct. 🙌

@ryuran Sorry I didn't see your follow up question. A _text content_ `max-height` is a requirement parameter of **shave** to truncate _text content_ within an element - **not** to set a `max-height` to the element itself.
