### ISSUE TITLE
insertAdjacentElement not supported by Firefox <48

### ISSUE THREAD

**Issue by AriLFrankel** [dollarshaveclub/shave#193]
## What Is the issue?

Element.insertAdjacentElement method is not supported in versions of Firefox below 48.

This impacts users on Windows 7, which is a significant number of employees at my company (Whole Foods Market)

## Provide issue context below using code examples, images, or links
On [line 65](https://github.com/AriLFrankel/shave/blob/master/src/shave.js#L65)
See support tables [here](https://caniuse.com/#search=insertAdjacentElement)

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by amoshydra** [comment]
@AriLFrankel They explained in https://github.com/dollarshaveclub/shave/issues/169#issuecomment-523088297 that this issue will not be fixed.

As a temporary workaround, I pinned shave version to `2.5.2` in my package.json
```diff
-    "shave": "^2.5.2",
+    "shave": "2.5.2",
 ```
