### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by Johann-S** [dollarshaveclub/shave#2]
Hi,

First of all it's a nice plugin 👏 

Is it possible for you to add compatibility informations ?

**Comment by yowainwright** [comment]
Noted: this will be _worked on/considered_ asap!

**Comment by Johann-S** [comment]
Thank you for your quick answer 👍

**Comment by yowainwright** [comment]
@Johann-S no problem! Please keep me posted on anything I can do to improve the plugin.
