### ISSUE TITLE
Truncate long words text

### ISSUE THREAD

**Issue by aspirisen** [dollarshaveclub/shave#22]
It works icorrect in case if the text is long i.e. link. For [example](http://codepen.io/anon/pen/woMGVR) the first paragraph.

**Comment by yowainwright** [comment]
@aspirisen Thanks for the note. 🙌  I need to update the code that's in my demos. They demo plugin code is 1 or 2 versions ago. 

Here you go: [Your example forked](http://codepen.io/yowainwright/pen/4171eca8f93276cd1c3b7a3f5711e878/)

*Example*
```
shave('p', 70, {spaces: false});
```
I'm going to make another issue for updating demo code. ♻️
