### ISSUE TITLE
Error thrown with Zepto

### ISSUE THREAD

**Issue by nrempel** [dollarshaveclub/shave#24]
An error is thrown when using with Zepto.

`shave.js:64 Uncaught TypeError: plugin.fn.extend is not a function(…)`

Looks like Zepto and JQuery have different namespaces for the extend function.

Related SO post: http://stackoverflow.com/questions/13211667/jquery-pluggin-zepto-fn-extend-is-undefined

**Comment by yowainwright** [comment]
Hey @nrempel. Thanks for pointing this out! We'll look into it as soon as possible! 🙌

**Comment by jakiestfu** [comment]
plugin.fn.shave = ... will solve this

**Comment by nrempel** [comment]
thanks all!
