### ISSUE TITLE
Is is possible return jQuery instance after called?

### ISSUE THREAD

**Issue by ShinyChang** [dollarshaveclub/shave#25]
jQuery method chaining is fantastic.

For example: 

```
$('selector').shave(maxheight).css({height: maxHeight});
```

But shave does not return the instance for now.

**Comment by jakiestfu** [comment]
Good idea!

**Comment by yowainwright** [comment]
Thanks for pointing this out @ShinyChang! 💪 We'll look into this as soon as possible.

**Comment by jakiestfu** [comment]
@yowainwright this one is an easy one.

Instead of returning the invocation of the shave function in the jQuery context, just return the this keyword instead.

shave(this, maxHeight, opts);
return this;

Sorry no syntax highlighting, on mah phone

**Comment by pwfisher** [comment]
Resolved by 5eaa9337e8b70f367acba78554206a2e9809ed16
