### ISSUE TITLE
Truncate text fail when container height has been set

### ISSUE THREAD

**Issue by ShinyChang** [dollarshaveclub/shave#26]
demo: 

https://jsbin.com/tudixum/4/edit?html,css,js,output

**Comment by yowainwright** [comment]
@ShinyChang why would someone want to truncate the text then? 😊

**Comment by pwfisher** [comment]
I think I like this idea. It makes shave easier to use. Usage stays simple, it just becomes more robust and less likely to run into frustrating failures.
