### ISSUE TITLE
IE 8 broken when no text content

### ISSUE THREAD

**Issue by ShinyChang** [dollarshaveclub/shave#29]
Hi there,

I used shave and got some trouble like below imgs:

![image](https://cloud.githubusercontent.com/assets/1590707/20355131/48f87a40-ac5b-11e6-954c-82af6b3ed9e1.png)

![image](https://cloud.githubusercontent.com/assets/1590707/20355151/58b90bfc-ac5b-11e6-890b-c5d11c24c31d.png)

I think the problem is I shave a  empty `<div/>`.

Update:
The problem is IE8 do not have `el.textContent`. Can use `el.innerText` as fallback.

**Comment by yowainwright** [comment]
@ShinyChang what percentage or your users are using ie8? 

Initially, since it is hard for me to test ie8 I'd like some awareness into your use case. 

It might almost be better to update the readme to say modern browsers rather than change more code to make the plugin work in ie8. 

What are your thoughts?

Thanks for the feedback! 👍

**Comment by ShinyChang** [comment]
@yowainwright ,
China piracy is rampant, pirated windows can not upgrade anything including IE. Some people migrate to Chrome or FireFox. But still have 30% user using IE8 for now.

 I totally agree no more code for old browser. I will find other polyfill to make sure shave works correct.

**Comment by ShinyChang** [comment]
Here is the polyfill. And it works perfect.

```
if (Object.defineProperty 
  && Object.getOwnPropertyDescriptor 
  && Object.getOwnPropertyDescriptor(Element.prototype, "textContent") 
  && !Object.getOwnPropertyDescriptor(Element.prototype, "textContent").get) {
  (function() {
    var innerText = Object.getOwnPropertyDescriptor(Element.prototype, "innerText");
    Object.defineProperty(Element.prototype, "textContent",
     {
       get: function() {
         return innerText.get.call(this);
       },
       set: function(s) {
         return innerText.set.call(this, s);
       }
     }
   );
  })();
}
```
Source: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

Maybe It can be documented in ReadMe. What you think @yowainwright

**Comment by yowainwright** [comment]
We can do much better then that but we have to test. 🤓 

Would you be able to help us test? 

If so, I'll make a PR for ie8 & include you. 

Thanks for the insight! 🙌

**Comment by yowainwright** [comment]
IE8 support is in progress. 🔧
