### ISSUE TITLE
Expose "done" callback

### ISSUE THREAD

**Issue by FezVrasta** [dollarshaveclub/shave#3]
It would be nice to have a callback to use to trigger an action once Shave finished to do its work.

It could be useful to hide the text with `opacity: 0` while the library is doing its work and show it once it finished.

**Comment by jakiestfu** [comment]
Pretty sure this library is synchronous.

Just write your code after the line that does the shaving

**Comment by FezVrasta** [comment]
No it isn't simply because the DOM rendering isn't.

If you notice, in the Codepen below, the text flashes during the rendering:
http://codepen.io/FezVrasta/pen/wzOXdX

**Comment by jakiestfu** [comment]
Pretty sure it's because your browser has to parse all of shave before it can hide the element.

Set its opacity to `0` with CSS, then when the particular element has been truncated, you can set it to `1`. I'm not seeing a flash anymore, are you @FezVrasta?

http://codepen.io/anon/pen/ORqExk

**Comment by FezVrasta** [comment]
ahah yes 🙂 thanks
