### ISSUE TITLE
When using {spaces: false}, CSS line-height can cause text to always truncate even when unnecessary

### ISSUE THREAD

**Issue by philklc** [dollarshaveclub/shave#32]
Here is a test page of this happening, the last character always get hidden and replaced with ellipsis even when there is clearly enough space.
http://jsbin.com/kaqanalira/edit?html,css,js,output

![spacesfalse](https://cloud.githubusercontent.com/assets/882957/21126513/a81cca18-c127-11e6-98e4-4dbf43e99b7b.png)

**Comment by yowainwright** [comment]
Thanks for sharing. 🙌

What is your exact use case? 

Are you trying to truncate both non-spaced and spaced languages with _shave_ in 1 call?

**Comment by philklc** [comment]
I am building a news website with a sidebar component that works similarly to a email client or RSS reader, trying to fit the title text in rows of a fixed size, in this case, 300x50px.

**Comment by yowainwright** [comment]
http://jsbin.com/fibozif/edit?html,css,js,output 
^ Does that example appear to work for you? 

(I apologize. I'm just trying to make sure that we're identifying the same thing)

**Comment by philklc** [comment]
I forgot to mention this requirement earlier: I am trying to display all the text in two lines, and truncate the text only if there is not enough space. In my example, with the 25px line-height, two lines of text should be 50px tall, this is why I passed 50 as the max-height parameter to shave.

In your example, given the 15px font-size and 1em line-height used, the last four paragraphs breaks into four lines, expanding the containing element's height to 60px (15x4=60). If I pass 60 instead of 50 as the max-height parameter, I would expect only the first two elements to be truncated by shave. However, it end up the same as my example: the last character of the third to fifth elements got truncated by shave.

**Comment by yowainwright** [comment]
Hmmm. I thought it was working ... ? I'll look again tomorrow. 

To note, (so I don't slow you down) I think there is a good chance that the conclusion of this issue will be an update to the `readme` and not a code change.

Based on what I understand, I'd recommend using a ratio for the line-height ALWAYS anyways 😊 & doing a separate `shave` call for spaced vs non-spaced languages.

Talk soon!

**Comment by philklc** [comment]
I am using unitless line-heights actually in my project, but please disregard this aspect of the example.

I used jQuery.dotdotdot in my previous projects, they don't have to distinguish between spaced vs non-spaced languages, instead they have an option for specifying breaking by letter instead of breaking by word. For my use case, their {wrap: 'letter'} option works well:
http://jsbin.com/vefehawuvu/edit?html,css,js,output

Is this something that shave can do in a future release? As jQuery.dotdotdot requires jQuery and is no longer actively maintained, and shave is a really compelling lightweight and dependency-free alternative.

**Comment by yowainwright** [comment]
In regards to my previous example, I'm not seeing 4 lines. I'm seeing this: 
![js_bin_-_collaborative_javascript_debugging](https://cloud.githubusercontent.com/assets/1074042/21155408/ed8f6106-c126-11e6-8f3d-54fa9f236985.jpg)
Which looks like it works ... ? (The screenshot is from a newer version of Chrome on a Mac). 
What browser/os are you trying to support? 

In regard to future options, I don't think we'll be offering more options unless very necessary. If there is a bug, we'll fix it but as I'm still learning about the issue you're describing - it seems that **shave** will work with the right css & usage. Keep me posted. I'm happy to help/chat about it! 🙌

**Comment by philklc** [comment]
Please refer to my latest example, which all <p> elements have a computed height of 30px, and I passed 30 as the max-height parameter to shave:
http://jsbin.com/vefehawuvu/edit?html,css,js,output

![problem](https://cloud.githubusercontent.com/assets/882957/21169172/dbd6264c-c1f4-11e6-8cde-6e63661244d4.png)

Just like the example, I intend to truncate multiple elements in one call and expect it to actually truncate text only when there is not enough room to display the text, and do nothing when all the text can already fit within the height given.

I tested with Chrome 54, Firefox 50 and IE11 on Windows 7.

**Comment by yowainwright** [comment]
Did you refer to the example that I provided for you? 

If so, did that appear to be working for you as the screen capture that I took suggested?

**Comment by yowainwright** [comment]
Hey @philklc!

While reviewing your most recent jsbin, it seems **shave** will work as you desire with minimal `css` or by changing the `truncate max height` to 32 rather than 30. 

Rather than go back & forth sharing jsbins 😊, it seems we need to discuss the philosophy of the **shave** plugin:

 > truncate text in the fastest most lightweight (kbs) way possible on the dom (or shadow dom). 

When creating the plugin, I realized that by using a `max-height` param we could truncate text far faster. You can read more about my considerations [here](http://engineering.dollarshaveclub.com/truncating-text/). 

Based on your comments, it seems like a [line-clamp](http://caniuse.com/#feat=css-line-clamp) css polyfill may more perfectly solve your use case. Shave will work too and will probably be lighter (kbs) but it does not approach text truncation how your suggesting in your comments. 🙌
