### ISSUE TITLE
Does not work on Chinese Mandarin characters.

### ISSUE THREAD

**Issue by puttykitties** [dollarshaveclub/shave#36]
Shave.js runs fine when it's using English characters, however when Chinese fonts are loaded, it doesn't seem to work. Any ideas?
![image](https://cloud.githubusercontent.com/assets/20024362/21513970/cc60a434-ccf9-11e6-95d3-a83d0e5e6185.png)

**Comment by yowainwright** [comment]
Yes, you have to use the non-spaced option. `spaces: false` http://codepen.io/yowainwright/pen/wzVgMp 

Let me know if that helps/works! 🙌

**Comment by puttykitties** [comment]
Sorry didn't take note of that! Thanks for the quick response. Cheers!

**Comment by briangonzalez** [comment]
Lovely exchange ❤️
