### ISSUE TITLE
1 word missing (Plain javascript codepen)

### ISSUE THREAD

**Issue by sspilleman** [dollarshaveclub/shave#37]
Hi,

I was trying the plain javascript demo, linked on your website. Looking at the dom inspector... I see there is one word ("hendrerit") missing between the displayed text (ends with justo) and the hidden section (starts with quis)... (justo hendrerit quis)

Sander

**Comment by yowainwright** [comment]
Great observation! I'll look into it soon! ~Thanks 🙌

**Comment by yowainwright** [comment]
@sspilleman Thank you SO MUCH for noticing that!!! That issue should be fixed. 🙏
