### ISSUE TITLE
Removes end of line in IE11

### ISSUE THREAD

**Issue by freginold** [dollarshaveclub/shave#38]
(This may be by design, so if it is, apologies in advance.)

I work somewhere where I can't install anything on my work PC, so I'm using Shave in the browser (IE 11).  When I call it on some HTML that has line breaks (`<br />` or `<br>`) it removes the line breaks when truncating (or maybe just doesn't apply them).

For example, this is the text before truncating:
![capture](https://cloud.githubusercontent.com/assets/16857063/21813462/566a7aae-d724-11e6-9a5e-dd6e280847ca.PNG)

and this is the same text after calling Shave on it:
![capture](https://cloud.githubusercontent.com/assets/16857063/21813439/3e18a8b8-d724-11e6-8964-0bbfefc50439.PNG)

I'm running Shave on a Windows 7 x86 machine in IE 11.  Unfortunately we're not allowed to install new programs so I can't test it in any other browsers.  Here's my HTML:

```html
<div id="parent">

<div id="child" class="divClass">
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
This is a lot of text that should get truncated so let's see if it works.<br><br>
</div>

</div>

<script src="shave.js"></script>

<script>

shave('#child', 35, {character: '...'});

</script>
```

Even after increasing the max height it still keeps going on the same line.

As a side note, Shave is a great plugin.  Very impressed with it.  Let me know if you want any more info.

**Comment by yowainwright** [comment]
@freginold Thank you so much for your feedback & liking shave! I'll look into your observation soon! 🙌

**Comment by yowainwright** [comment]
@freginold you're very right on both accounts. 
1.   Shave, shaves text so the <br><br> are removed by design
```javascript
// ~line 21 of src/shave.js
const textProp = el.textContent === undefined ? 'innerText' : 'textContent';
```
2.   Shave will remove the line-breaks (`<br>`). 

-  This is in all browsers.

Can I help at all with the shave implementation you're working on? 
What's the scenario where a bunch of line breaks are added? (Happy to help 😃)

**Comment by freginold** [comment]
@yowainwright thanks for clearing that up!  I should have looked closer at the source code.  It wasn't breaking anything I was working on... I was just trying to get familiar with it and playing around with it.  Can't really think of a use case where those line breaks would be required and couldn't be replicated another way, it was just a quick test page I made up to play around with Shave.

Thanks for the info!

**Comment by yowainwright** [comment]
@freginold you bet!
