### ISSUE TITLE
Possible to pass a DOM node instead of a selector?

### ISSUE THREAD

**Issue by syropian** [dollarshaveclub/shave#39]
We have an instance where we need to set different max heights for each instance of an element. i guess this could be done with jQuery using `each`, but can it be done using vanilla JS? I'm guessing `querySelectorAll` gets called from the argument.

**Comment by yowainwright** [comment]
A dom node would work as a `target`. However, to your point about different max heights for the same `target`:

-  it seems you're on the right path—looping over each `target` 
-  then, within the loop, supply the desired max height for  shave's 2nd arg 

jQuery or vanilla js looping should work using something like [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) or maybe [for ...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)


I **think** it could look something like:
```
for (const el of els) {
  const maxHeight = el.offsetHeight - someNumberOrSomething;
  shave(el, maxHeight);
}
```

**Comment by syropian** [comment]
Cool, thanks! I just wanted to make sure I could pass a ref to a node as opposed to a selector string to the constructor.

**Comment by yowainwright** [comment]
@syropian fursur!
