### ISSUE TITLE
Set element's max-height to avoid reflow

### ISSUE THREAD

**Issue by zaaack** [dollarshaveclub/shave#43]
Changing the original element's height would cause the browser to reflow, in a very very long page,  this might be a performance issue, what about setting element's max-height before the binary search, and using scrollHeight or creating a detached element with an absolute position?

**Comment by yowainwright** [comment]
Hey @zaaack! Sorry, I didn't see this message until now. I'll look asap!

**Comment by zaaack** [comment]
Hei, never mind, thanks for your awesome project!
