### ISSUE TITLE
Text is truncated even though there's enough height to fit

### ISSUE THREAD

**Issue by qsjchen** [dollarshaveclub/shave#46]
Text was getting truncated even though there's enough height to fit all text. This happens when offsetHeight is exactly equal to maxHeight. On line 43 of shave.js, the comparison should be less than or equal to. I was forced to add an extra pixel to not get my text truncated enough though there's enough space.

**Comment by yowainwright** [comment]
@qsjchen I think there is another approach to this and since the issue you raised has been brought more than 1x. I will look into it. Thanks for your PR! 🙏
