### ISSUE TITLE
Website example paragraph gets shorter and shorter on multiple clicks.

### ISSUE THREAD

**Issue by KrisOlszewski** [dollarshaveclub/shave#5]
Hi there, thanks for a great plugin! I noticed a bug on the website example. If you keep clicking on Truncate Text / Reset button, then the paragraph will get shorter and shorter. In the end you end up with `Shave is a zero dependency javascriptthethe originaltact!`. It's pretty easy to replicate.

**Comment by yowainwright** [comment]
@KrisOlszewski Thanks for pointing that out - it came with the optimization (~2x faster) & will be fixed as soon as possible. 🍻

**Comment by sebastienbarre** [comment]
The irony though :)

**Comment by yowainwright** [comment]
Fixed @KrisOlszewski . Thanks for pointing that out!
