### ISSUE TITLE
Truncate to number of lines

### ISSUE THREAD

**Issue by pymarco** [dollarshaveclub/shave#52]
A nice feature that trunk8.js has is to truncate to a set number of lines. Is this possible with Shave?

http://jrvis.com/trunk8/?rel=github#lines

**Comment by yowainwright** [comment]
Shave doesn't do that because calculating the number of lines would make the plugin a fair amount larger (file size). 

Instead, with Shave, the max height is used—which _could_ be the calculated height of the line-height by a developer using the plugin. 😊

**Comment by pymarco** [comment]
ok thanks
