### ISSUE TITLE
Why it remove html tags inside selected element?

### ISSUE THREAD

**Issue by webcredo** [dollarshaveclub/shave#6]
Why it remove html tags inside selected element?

**Comment by yowainwright** [comment]
I apologize. I don't understand the question @webcredo .

**Comment by webcredo** [comment]
for example in this code it strip list tags and text will be shown in 1 line.

```
<script>
$('.shave').shave(200);
</script>
<div class="shave">
<ul>
<li>list item</li>
<li>list item</li>
<li>list item</li>
</ul>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
```

**Comment by yowainwright** [comment]
Because (copying from the readme):
> Shave is a zero dependency javascript plugin that truncates multi-line text to fit within a **html element** based on a set max-height.

I should clarify that more in the readme. Thanks for pointing that out @webcredo

**Comment by pwfisher** [comment]
We don't support tags within the target element.

We take the `element.textContent` which is a text representation of the content (no child tag markup). When we rewrite the content of the target element, any child nodes are replaced with the truncated text.

We could add a check to skip target elements which have child nodes which would be destroyed.

**Comment by yowainwright** [comment]
@webcredo I'm going to close this issue after I clarify this in the **readme**. @pwfisher I don't think that is necessary because that becomes an over extension of the product's goal.

**Comment by yowainwright** [comment]
@webcredo the readme is updated - see the sentence close to the bottom of the page. Thanks for pointing that out. 🙌

**Comment by jakiestfu** [comment]
What if I had a `p` tag that contained an `a` tag?

**Comment by timmyrosen** [comment]
Really liked this until I noticed it stripped all html tags. Unusable for me.
