### ISSUE TITLE
Truncate text in the middle

### ISSUE THREAD

**Issue by pavel06081991** [dollarshaveclub/shave#66]
At my current project we need for dots to appear in the middle of text instead of end of text. Could you please add this feature? It would be great if this library had option where you want dots to appear(at the begging of text, at the end, in the middle).

**Comment by yowainwright** [comment]
@pavel06081991 could you add a mock or image so that I can understand your question better?

**Comment by danelowe** [comment]
I think they will have been referring to this kind of functionality:

https://www.w3.org/wiki/Text-overflow_middle_cropping

I solved by adding the ability to specify a function to control placement of the ellipsis, which allows us to create our own algorithm for shaving product titles that have sizes/colours we want to keep at the end of them. 

E.g.  with my quick and dirty typescript port:

In the library:
```
// ...
    // Binary search for number of words which can fit in allotted height
    let max = words.length - 1;
    let min = 0;
    let pivot;

    let postfix = '';
    if (opts.placement) {
      postfix = opts.placement(words);
    }

    while (min < max) {
      pivot = (min + max + 1) >> 1; // eslint-disable-line no-bitwise
      (el as any)[textProp] = words.slice(0, pivot).join(' ') + postfix;
      el.insertAdjacentHTML('beforeend', charHtml);
      if (el.offsetHeight > maxHeight) max = pivot - 1;
      else min = pivot;
    }

    (el as any)[textProp] = words.slice(0, max).join(' ');
    el.insertAdjacentHTML('beforeend', charHtml);
    el.insertAdjacentText('beforeend', postfix);
// ...
```

Using with a custom ellipsis placement function in my code:
```
      const placement = isTitle ? (words: string[]) => {
        const postfix = words.pop();
        const w = words.pop() || '';
        if ((w.length <= 5) && /\d/.test(w)) {
          return ' ' + w + ' ' + postfix;
        } else {
          words.push(w);
          return ' ' + postfix;
        }
      } : undefined;
      shave(ell as HTMLDivElement, maxHeight, {placement});
```
