### ISSUE TITLE
Unshave support.

### ISSUE THREAD

**Issue by vivaxy** [dollarshaveclub/shave#67]
It'll be better if `shave( /* ... */ )` provides a decent way to restore everything to it's origin.
Now, I have to set the innerHTML to it's original text. Sometimes I am not sure about what it was before.

Maybe like `shave( /* ... */ )` returns a function, and we call it to reset everything.

**Comment by yowainwright** [comment]
Hey, thanks for the note @vivaxy ! 

Why doesn't it work to _shave_ the _shaved_ element?

In example:
```javascript
shave('element')
// then, on another event or something
shave('element')
```
----

[`.textcontent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) should do that for free—unless there needs to be ie8 support ...?

**Comment by vivaxy** [comment]
`shave the shaved element works`. But in my situation, I have a button to toggle the shaved status. So it's better to have a method to do the "unshave" stuff.

**Comment by yowainwright** [comment]
`.textContent` **is** what is used to truncate text so if you _shave_ the shaved element it should be the same. 
If you view the [demo](https://dollarshaveclub.github.io/shave/), I think it may be doing exactly what we're discussing ...?

**Comment by yowainwright** [comment]
@vivaxy before I review the PR, did you review the demo as mentioned above?—Why does it not work for your needs? 

I need to understand the issue fully so that I can address it moving forward.

**Comment by vivaxy** [comment]
The demo works for my need.
What I did was that I wrap the textContent or innerText prop, the element and the original full text into a single function for better usage. I won't have the users to memorize the original text and to select the element again.
It's ok that you don't think it necessary.
Thanks for your detailed replies. 🙂️

**Comment by yowainwright** [comment]
Thanks for looking @vivaxy 🙏
