### ISSUE TITLE
Not working for one long word

### ISSUE THREAD

**Issue by aivaras-b** [dollarshaveclub/shave#77]
Hi, seems like shave is not working when you want to truncate one long word even with spaces set to false. Example: https://codepen.io/anon/pen/QqogaJ

**Comment by yowainwright** [comment]
Its b/c technically the line height never goes about 70px. 
Here's an [example](https://codepen.io/yowainwright/pen/ZaWZvE) where the max height is set to 10. Something happens that is not perfect ...but that has do with css joke (not shave).
![flat 800x800 070 f](https://user-images.githubusercontent.com/1074042/32413215-e2fdd26e-c1c9-11e7-9be7-4e5f06f5db0d.jpg)

----

Thanks for your note
