### ISSUE TITLE
startTime undefined in jQuery example Codepen

### ISSUE THREAD

**Issue by HarryPhillips** [dollarshaveclub/shave#8]
Not technically an issue with shave, however, time elapsed is displaying as empty. The [jQuery example Codepen](http://codepen.io/yowainwright/pen/c35ad7a281bc58ce6f89d2adb94c5d14/) is missing the following from line 71:

```javascript
const startTime = new Date();
```

**Comment by yowainwright** [comment]
👍 Will fix!

**Comment by yowainwright** [comment]
@HarryPhillips Fixed. Thanks for pointing that out. 🍻
