### ISSUE TITLE
Enhancement:  Option to disable inserting full text into DOM

### ISSUE THREAD

**Issue by clotton** [dollarshaveclub/shave#81]
It's great that this plugin automatically inserts a hidden element in the DOM with the full (untruncated) text.  But it might be nice to make an option to disable that behaviour if desired.

**Comment by yowainwright** [comment]
@clotton to keep this utility plugin as small as possible, it has been a choice to remove options that can be manipulated with css or minimal javascript. 

Let me know if I can help you beyond this note! 

Thank you! 🙏
