### ISSUE TITLE
Use scrollHeight instead of offsetHeight

### ISSUE THREAD

**Issue by afreix** [dollarshaveclub/shave#86]
If the text you want to truncate is a child of a parent who's height you use as the maxHeight, then shave will won't truncate. The offsetHeight will equal the maxHeight, because the overflowing text doesn't affect offsetHeight. If offsetHeight is replaced by scrollHeight, this fixes the problem, and doesn't break any existing use cases that I'm aware of

This also fixed a very quirky bug potentially related to flexbox and/or React where offsetHeight was not updating as text was being truncated. It's quite difficult to reproduce, but I could try if necessary.

I'm happy to submit a PR

**Comment by yowainwright** [comment]
@afreix yes, please submit a PR! Thanks for your considerate comment! 🙏

**Comment by afreix** [comment]
Turns out that it had to do with flexbox. A min-width is required on all flex-items that are parents of truncated text, so after setting a min-width, scrollHeight is no longer necessary
