### ISSUE TITLE
Return a boolean representing whether truncation occurred

### ISSUE THREAD

**Issue by afreix** [dollarshaveclub/shave#87]
It would be nice to return whether or not truncation occurred for those consuming this utility. Happy to submit a PR if this is something you also think would be valuable

**Comment by yowainwright** [comment]
Could you explain why this would be valuable?

Also, sorry I didn’t notice this issue before.

**Comment by afreix** [comment]
No problem! And in our app, we conditionally apply a tooltip with the full text depending on whether truncation occurred

**Comment by yowainwright** [comment]
@afreix how are you seeing this feature working?...Like adding a CSS class if the element is shaved?

**Comment by afreix** [comment]
More simply than that. We just change shave to return a boolean (true meaning some text was truncated or false meaning no truncation occurred).

We'll initialize a didTruncate variable to false, and then set it to true in an else block on line 42

**Comment by yowainwright** [comment]
Hey @afreix, Submit a PR. It will be reivewed.
